"use client";

import React, { useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { QuizPlayer } from "@/components/quiz/QuizPlayer";
import { Quiz } from "@/components/quiz/QuizCard";
import { getQuizColor } from '@/lib/colors';

const DATA: Quiz[] = [
	{ id: 12, slug: "12", title: "Shape Up, Pumpkins, Famous First Words, Crazes, and Next In Sequence.", blurb: "A weekly selection mixing patterns, pop culture and logic.", weekISO: "2024-01-15", colorHex: getQuizColor(12), status: "available" },
	{ id: 11, slug: "11", title: "Opposite Day, Lights, Common Ground, Robots Etc, and First Ladies.", blurb: "Wordplay meets trivia.", weekISO: "2024-01-08", colorHex: getQuizColor(11), status: "available" },
	{ id: 10, slug: "10", title: "Back to the Past, Name That Nation, Name the Other, Analog Games, and What Does It Stand For?", blurb: "History, geography and acronyms.", weekISO: "2024-01-01", colorHex: getQuizColor(10), status: "available" },
	{ id: 9, slug: "9", title: "Holiday Trivia, Winter Sports, Year End Review, and Festive Fun.", blurb: "Seasonal mixed bag.", weekISO: "2023-12-25", colorHex: getQuizColor(9), status: "available" },
	{ id: 8, slug: "8", title: "Movie Magic, Tech Trends, Sports Moments, and Pop Culture.", blurb: "Headlines and highlights.", weekISO: "2023-12-18", colorHex: getQuizColor(8), status: "available" },
	{ id: 7, slug: "7", title: "World Wonders, Historical Events, Science Facts, and Geography.", blurb: "Curiosities around the world.", weekISO: "2023-12-11", colorHex: getQuizColor(7), status: "available" },
	{ id: 6, slug: "6", title: "Literature Classics, Music Legends, Art Movements, and Cultural Icons.", blurb: "Explore the arts and humanities.", weekISO: "2023-12-04", colorHex: getQuizColor(6), status: "available" },
	{ id: 5, slug: "5", title: "Space Exploration, Ocean Depths, Animal Kingdom, and Natural Phenomena.", blurb: "Discover the wonders of nature.", weekISO: "2023-11-27", colorHex: getQuizColor(5), status: "available" },
	{ id: 4, slug: "4", title: "Food & Drink, Cooking Techniques, World Cuisines, and Culinary History.", blurb: "A feast for the mind.", weekISO: "2023-11-20", colorHex: getQuizColor(4), status: "available" },
	{ id: 3, slug: "3", title: "Sports Legends, Olympic Moments, World Records, and Athletic Achievements.", blurb: "Celebrate sporting excellence.", weekISO: "2023-11-13", colorHex: getQuizColor(3), status: "available" },
	{ id: 2, slug: "2", title: "Mathematics Puzzles, Logic Problems, Number Patterns, and Brain Teasers.", blurb: "Exercise your logical mind.", weekISO: "2023-11-06", colorHex: getQuizColor(2), status: "available" },
	{ id: 1, slug: "1", title: "Famous Inventions, Scientific Discoveries, Medical Breakthroughs, and Innovation.", blurb: "Celebrate human ingenuity.", weekISO: "2023-10-30", colorHex: getQuizColor(1), status: "available" }
];

// Mock quiz data with questions and rounds
const QUIZ_DATA: Record<string, { questions: any[]; rounds: any[] }> = {
	"12": {
		rounds: [
			{ number: 1, title: "Shape Up", blurb: "Time to get in shape! Questions about forms, figures, and geometry." },
			{ number: 2, title: "Pumpkins", blurb: "Orange you glad? All about the beloved autumn squash." },
			{ number: 3, title: "Famous First Words", blurb: "How well do you know these iconic opening lines?" },
			{ number: 4, title: "Crazes", blurb: "Remember these trends that swept the world?" },
			{ number: 5, title: "Next In Sequence", blurb: "Can you spot the pattern and predict what comes next?" },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What colour is directly opposite purple on a traditional RYB colour wheel?", answer: "Yellow", submittedBy: "Miss Shannon, Loretto Kiribilli NSW", submissionDisplayStyle: "full" },
			{ id: 2, roundNumber: 1, question: "In literature, what word is the opposite of a prologue?", answer: "Epilogue" },
			{ id: 3, roundNumber: 1, question: "The antipode (direct opposite point of the earth) to Auckland, New Zealand lies in the southern region of which European country: France, Spain, or Germany?", answer: "Spain", submittedBy: "Steve G", submissionDisplayStyle: "first_name" },
			{ id: 4, roundNumber: 1, question: "When used to refer to moon phases, what verb is the opposite of \"to wax\"?", answer: "To wane" },
			{ id: 5, roundNumber: 1, question: "On 3 December 2007, who became the first of the three federal Opposition leaders during Kevin Rudd's time as Prime Minister?", answer: "Brendan Nelson" },
			{ id: 6, roundNumber: 1, question: "What is the geometric term for a shape with eight sides?", answer: "Octagon" },
			{ id: 7, roundNumber: 2, question: "In which hemisphere are pumpkins native?", answer: "Western Hemisphere (North America)" },
			{ id: 8, roundNumber: 2, question: "What pigment gives pumpkins their orange color?", answer: "Beta-carotene" },
			{ id: 9, roundNumber: 2, question: "Which US state produces the most pumpkins?", answer: "Illinois" },
			{ id: 10, roundNumber: 2, question: "What is a male pumpkin flower called?", answer: "Stamen" },
			{ id: 11, roundNumber: 2, question: "Pumpkins are 90% made of what?", answer: "Water", submittedBy: "Year 9 St Augustine's College", submissionDisplayStyle: "full" },
			{ id: 12, roundNumber: 2, question: "What is the largest pumpkin ever recorded?", answer: "Over 2,700 pounds" },
			{ id: 13, roundNumber: 3, question: "Which novel begins with 'Call me Ishmael'?", answer: "Moby-Dick" },
			{ id: 14, roundNumber: 3, question: "'It was the best of times, it was the worst of times' opens which novel?", answer: "A Tale of Two Cities" },
			{ id: 15, roundNumber: 3, question: "Which book starts with 'In a hole in the ground there lived a hobbit'?", answer: "The Hobbit" },
			{ id: 16, roundNumber: 3, question: "'It is a truth universally acknowledged' starts which Jane Austen novel?", answer: "Pride and Prejudice" },
			{ id: 17, roundNumber: 3, question: "Which dystopian novel begins with 'It was a bright cold day in April'?", answer: "1984" },
			{ id: 18, roundNumber: 3, question: "What novel starts with 'It was a pleasure to burn'?", answer: "Fahrenheit 451" },
			{ id: 19, roundNumber: 4, question: "What toy craze involved small beanbag animals?", answer: "Beanie Babies" },
			{ id: 20, roundNumber: 4, question: "Which dance craze involved a horse-riding motion?", answer: "Gangnam Style" },
			{ id: 21, roundNumber: 4, question: "What fidget toy became wildly popular in 2017?", answer: "Fidget Spinner" },
			{ id: 22, roundNumber: 4, question: "Which 1970s craze involved a plastic hoop?", answer: "Hula Hoop" },
			{ id: 23, roundNumber: 4, question: "What virtual pet on a keychain was a 1990s phenomenon?", answer: "Tamagotchi" },
			{ id: 24, roundNumber: 4, question: "What social media app became a craze in 2020?", answer: "TikTok" },
			{ id: 25, roundNumber: 5, question: "Complete the sequence: 2, 4, 8, 16, __?", answer: "32" },
		]
	},
	"279": {
		rounds: [
			{ number: 1, title: "Shape Up", blurb: "Time to get in shape! Questions about forms, figures, and geometry." },
			{ number: 2, title: "Pumpkins", blurb: "Orange you glad? All about the beloved autumn squash." },
			{ number: 3, title: "Famous First Words", blurb: "How well do you know these iconic opening lines?" },
			{ number: 4, title: "Crazes", blurb: "Remember these trends that swept the world?" },
			{ number: 5, title: "Next In Sequence", blurb: "Can you spot the pattern and predict what comes next?" },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What colour is directly opposite purple on a traditional RYB colour wheel?", answer: "Yellow", submittedBy: "Miss Shannon, Loretto Kiribilli NSW", submissionDisplayStyle: "full" },
			{ id: 2, roundNumber: 1, question: "In literature, what word is the opposite of a prologue?", answer: "Epilogue" },
			{ id: 3, roundNumber: 1, question: "The antipode (direct opposite point of the earth) to Auckland, New Zealand lies in the southern region of which European country: France, Spain, or Germany?", answer: "Spain", submittedBy: "Steve G", submissionDisplayStyle: "first_name" },
			{ id: 4, roundNumber: 1, question: "When used to refer to moon phases, what verb is the opposite of \"to wax\"?", answer: "To wane" },
			{ id: 5, roundNumber: 1, question: "On 3 December 2007, who became the first of the three federal Opposition leaders during Kevin Rudd's time as Prime Minister?", answer: "Brendan Nelson" },
			{ id: 6, roundNumber: 1, question: "What is the geometric term for a shape with eight sides?", answer: "Octagon" },
			{ id: 7, roundNumber: 2, question: "In which hemisphere are pumpkins native?", answer: "Western Hemisphere (North America)" },
			{ id: 8, roundNumber: 2, question: "What pigment gives pumpkins their orange color?", answer: "Beta-carotene" },
			{ id: 9, roundNumber: 2, question: "Which US state produces the most pumpkins?", answer: "Illinois" },
			{ id: 10, roundNumber: 2, question: "What is a male pumpkin flower called?", answer: "Stamen" },
			{ id: 11, roundNumber: 2, question: "Pumpkins are 90% made of what?", answer: "Water", submittedBy: "Year 9 St Augustine's College", submissionDisplayStyle: "full" },
			{ id: 12, roundNumber: 2, question: "What is the largest pumpkin ever recorded?", answer: "Over 2,700 pounds" },
			{ id: 13, roundNumber: 3, question: "Which novel begins with 'Call me Ishmael'?", answer: "Moby-Dick" },
			{ id: 14, roundNumber: 3, question: "'It was the best of times, it was the worst of times' opens which novel?", answer: "A Tale of Two Cities" },
			{ id: 15, roundNumber: 3, question: "Which book starts with 'In a hole in the ground there lived a hobbit'?", answer: "The Hobbit" },
			{ id: 16, roundNumber: 3, question: "'It is a truth universally acknowledged' starts which Jane Austen novel?", answer: "Pride and Prejudice" },
			{ id: 17, roundNumber: 3, question: "Which dystopian novel begins with 'It was a bright cold day in April'?", answer: "1984" },
			{ id: 18, roundNumber: 3, question: "What novel starts with 'It was a pleasure to burn'?", answer: "Fahrenheit 451" },
			{ id: 19, roundNumber: 4, question: "What toy craze involved small beanbag animals?", answer: "Beanie Babies" },
			{ id: 20, roundNumber: 4, question: "Which dance craze involved a horse-riding motion?", answer: "Gangnam Style" },
			{ id: 21, roundNumber: 4, question: "What fidget toy became wildly popular in 2017?", answer: "Fidget Spinner" },
			{ id: 22, roundNumber: 4, question: "Which 1970s craze involved a plastic hoop?", answer: "Hula Hoop" },
			{ id: 23, roundNumber: 4, question: "What virtual pet on a keychain was a 1990s phenomenon?", answer: "Tamagotchi" },
			{ id: 24, roundNumber: 4, question: "What social media app became a craze in 2020?", answer: "TikTok" },
			{ id: 25, roundNumber: 5, question: "Complete the sequence: 2, 4, 8, 16, __?", answer: "32" },
		]
	},
	"11": {
		rounds: [
			{ number: 1, title: "Opposite Day", blurb: "Everything is backwards today! Can you flip your thinking?" },
			{ number: 2, title: "Lights", blurb: "Let there be light! Questions about illumination and brightness." },
			{ number: 3, title: "Common Ground", blurb: "Finding what connects us all in surprising ways." },
			{ number: 4, title: "Robots Etc", blurb: "Artificial intelligence, automatons, and mechanical marvels!" },
			{ number: 5, title: "First Ladies", blurb: "Celebrating the women behind powerful leaders." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What is the opposite of hot?", answer: "Cold" },
			{ id: 2, roundNumber: 1, question: "What is the antonym of 'big'?", answer: "Small" },
			{ id: 3, roundNumber: 1, question: "What's the opposite of 'fast'?", answer: "Slow" },
			{ id: 4, roundNumber: 1, question: "What is the reverse of 'up'?", answer: "Down" },
			{ id: 5, roundNumber: 1, question: "What's the opposite of 'day'?", answer: "Night" },
			{ id: 6, roundNumber: 1, question: "What is the opposite of 'happy'?", answer: "Sad" },
			{ id: 7, roundNumber: 2, question: "Who invented the light bulb?", answer: "Thomas Edison" },
			{ id: 8, roundNumber: 2, question: "What is the speed of light in a vacuum?", answer: "299,792 km/s" },
			{ id: 9, roundNumber: 2, question: "What year were LED lights invented?", answer: "1962" },
			{ id: 10, roundNumber: 2, question: "Aurora Borealis is also known as what?", answer: "Northern Lights" },
			{ id: 11, roundNumber: 2, question: "What gas do traditional fluorescent lights contain?", answer: "Mercury vapor" },
			{ id: 12, roundNumber: 2, question: "What is the unit of measurement for light intensity?", answer: "Lumens" },
			{ id: 13, roundNumber: 3, question: "What language is most widely spoken worldwide?", answer: "English" },
			{ id: 14, roundNumber: 3, question: "What is the most common blood type?", answer: "O positive" },
			{ id: 15, roundNumber: 3, question: "What element is most abundant in Earth's atmosphere?", answer: "Nitrogen" },
			{ id: 16, roundNumber: 3, question: "What is the most practiced religion?", answer: "Christianity" },
			{ id: 17, roundNumber: 3, question: "What currency is used in most countries?", answer: "US Dollar" },
			{ id: 18, roundNumber: 3, question: "What is the most common element in the human body?", answer: "Oxygen" },
			{ id: 19, roundNumber: 4, question: "What was the first industrial robot called?", answer: "Unimate" },
			{ id: 20, roundNumber: 4, question: "Which company created the robot dog 'Aibo'?", answer: "Sony" },
			{ id: 21, roundNumber: 4, question: "What does AI stand for?", answer: "Artificial Intelligence" },
			{ id: 22, roundNumber: 4, question: "Who wrote 'I, Robot'?", answer: "Isaac Asimov" },
			{ id: 23, roundNumber: 4, question: "What is the humanoid robot from Boston Dynamics called?", answer: "Atlas" },
			{ id: 24, roundNumber: 4, question: "What year was the first robot patent filed?", answer: "1954" },
			{ id: 25, roundNumber: 5, question: "Who was the first US First Lady?", answer: "Martha Washington" },
		]
	},
	"10": {
		rounds: [
			{ number: 1, title: "Back to the Past", blurb: "Journey through history's most memorable moments!" },
			{ number: 2, title: "Name That Nation", blurb: "Test your geography and world knowledge." },
			{ number: 3, title: "Name the Other", blurb: "Can you identify the missing piece of these famous pairs?" },
			{ number: 4, title: "Analog Games", blurb: "Before screens took over, these games ruled!" },
			{ number: 5, title: "What Does It Stand For?", blurb: "Decode these acronyms and abbreviations." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "In what year did World War II end?", answer: "1945" },
			{ id: 2, roundNumber: 1, question: "When did the Berlin Wall fall?", answer: "1989" },
			{ id: 3, roundNumber: 1, question: "What year did humans first land on the moon?", answer: "1969" },
			{ id: 4, roundNumber: 1, question: "When was the Declaration of Independence signed?", answer: "1776" },
			{ id: 5, roundNumber: 1, question: "In what year did the Titanic sink?", answer: "1912" },
			{ id: 6, roundNumber: 1, question: "What year did the internet become publicly available?", answer: "1991" },
			{ id: 7, roundNumber: 2, question: "What is the capital of Japan?", answer: "Tokyo" },
			{ id: 8, roundNumber: 2, question: "Which country has the most pyramids?", answer: "Sudan" },
			{ id: 9, roundNumber: 2, question: "What is the smallest country in the world?", answer: "Vatican City" },
			{ id: 10, roundNumber: 2, question: "Which nation has the longest coastline?", answer: "Canada" },
			{ id: 11, roundNumber: 2, question: "In which country is the ancient city of Petra?", answer: "Jordan" },
			{ id: 12, roundNumber: 2, question: "What is the largest country by land area?", answer: "Russia" },
			{ id: 13, roundNumber: 3, question: "Simon & __?", answer: "Garfunkel" },
			{ id: 14, roundNumber: 3, question: "Romeo & __?", answer: "Juliet" },
			{ id: 15, roundNumber: 3, question: "Batman & __?", answer: "Robin" },
			{ id: 16, roundNumber: 3, question: "Bonnie & __?", answer: "Clyde" },
			{ id: 17, roundNumber: 3, question: "Salt & __?", answer: "Pepper" },
			{ id: 18, roundNumber: 3, question: "Tom & __?", answer: "Jerry" },
			{ id: 19, roundNumber: 4, question: "What board game involves buying property?", answer: "Monopoly" },
			{ id: 20, roundNumber: 4, question: "In which game do you sink your opponent's fleet?", answer: "Battleship" },
			{ id: 21, roundNumber: 4, question: "What game uses colored cards with numbers?", answer: "UNO" },
			{ id: 22, roundNumber: 4, question: "Which game involves removing wooden blocks?", answer: "Jenga" },
			{ id: 23, roundNumber: 4, question: "What strategy game uses black and white stones?", answer: "Go" },
			{ id: 24, roundNumber: 4, question: "What card game involves matching sets?", answer: "Rummy" },
			{ id: 25, roundNumber: 5, question: "What does NASA stand for?", answer: "National Aeronautics and Space Administration" },
		]
	},
	"9": {
		rounds: [
			{ number: 1, title: "Holiday Trivia", blurb: "Celebrate the festive season!" },
			{ number: 2, title: "Winter Sports", blurb: "Cool sports for cold weather." },
			{ number: 3, title: "Year End Review", blurb: "Looking back at the year that was." },
			{ number: 4, title: "Festive Fun", blurb: "Holiday cheer and celebrations!" },
			{ number: 5, title: "Winter Wonders", blurb: "Amazing facts about the coldest season." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What date is Christmas?", answer: "December 25" },
			{ id: 2, roundNumber: 1, question: "What is the first day of Hanukkah called?", answer: "First Night" },
			{ id: 3, roundNumber: 1, question: "In which country did the tradition of Christmas trees originate?", answer: "Germany" },
			{ id: 4, roundNumber: 1, question: "What is the day after Christmas called?", answer: "Boxing Day" },
			{ id: 5, roundNumber: 1, question: "How many days of Christmas are there in the song?", answer: "12" },
			{ id: 6, roundNumber: 1, question: "What is Kwanzaa?", answer: "African-American holiday" },
			{ id: 7, roundNumber: 2, question: "What sport is played at the Winter Olympics?", answer: "Ice Hockey" },
			{ id: 8, roundNumber: 2, question: "What is curling?", answer: "A winter sport with stones" },
			{ id: 9, roundNumber: 2, question: "What is the fastest winter sport?", answer: "Skeleton" },
			{ id: 10, roundNumber: 2, question: "What sport involves jumping off a ramp on skis?", answer: "Ski Jumping" },
			{ id: 11, roundNumber: 2, question: "What is biathlon?", answer: "Cross-country skiing and shooting" },
			{ id: 12, roundNumber: 2, question: "What is the most popular winter sport?", answer: "Skiing" },
			{ id: 13, roundNumber: 3, question: "What year is it?", answer: "2023" },
			{ id: 14, roundNumber: 3, question: "What was the biggest news story of the year?", answer: "Various answers" },
			{ id: 15, roundNumber: 3, question: "What technology trend dominated this year?", answer: "AI" },
			{ id: 16, roundNumber: 3, question: "What was the most popular movie?", answer: "Various answers" },
			{ id: 17, roundNumber: 3, question: "What was the biggest sporting event?", answer: "Various answers" },
			{ id: 18, roundNumber: 3, question: "What was the most talked about TV show?", answer: "Various answers" },
			{ id: 19, roundNumber: 4, question: "What do people hang on Christmas trees?", answer: "Ornaments" },
			{ id: 20, roundNumber: 4, question: "What is a popular holiday drink?", answer: "Eggnog" },
			{ id: 21, roundNumber: 4, question: "What do people leave for Santa?", answer: "Cookies and milk" },
			{ id: 22, roundNumber: 4, question: "What is a popular holiday song?", answer: "Jingle Bells" },
			{ id: 23, roundNumber: 4, question: "What is a Yule log?", answer: "A traditional Christmas dessert" },
			{ id: 24, roundNumber: 4, question: "What do people exchange during holidays?", answer: "Gifts" },
			{ id: 25, roundNumber: 5, question: "What is the coldest temperature ever recorded?", answer: "-128.6°F" },
		]
	},
	"8": {
		rounds: [
			{ number: 1, title: "Movie Magic", blurb: "Lights, camera, action!" },
			{ number: 2, title: "Tech Trends", blurb: "The latest in technology." },
			{ number: 3, title: "Sports Moments", blurb: "Memorable sporting achievements." },
			{ number: 4, title: "Pop Culture", blurb: "What's trending now." },
			{ number: 5, title: "Entertainment", blurb: "Fun and games!" },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What was the highest grossing movie?", answer: "Various" },
			{ id: 2, roundNumber: 1, question: "Who won Best Actor?", answer: "Various" },
			{ id: 3, roundNumber: 1, question: "What is the longest movie?", answer: "Various" },
			{ id: 4, roundNumber: 1, question: "What movie franchise has the most films?", answer: "James Bond" },
			{ id: 5, roundNumber: 1, question: "What is the most expensive movie ever made?", answer: "Various" },
			{ id: 6, roundNumber: 1, question: "What movie won Best Picture?", answer: "Various" },
			{ id: 7, roundNumber: 2, question: "What is the latest iPhone?", answer: "iPhone 15" },
			{ id: 8, roundNumber: 2, question: "What is ChatGPT?", answer: "AI chatbot" },
			{ id: 9, roundNumber: 2, question: "What is the most popular programming language?", answer: "JavaScript" },
			{ id: 10, roundNumber: 2, question: "What is blockchain?", answer: "Distributed ledger technology" },
			{ id: 11, roundNumber: 2, question: "What is 5G?", answer: "Fifth generation mobile network" },
			{ id: 12, roundNumber: 2, question: "What is quantum computing?", answer: "Advanced computing technology" },
			{ id: 13, roundNumber: 3, question: "Who won the World Cup?", answer: "Various" },
			{ id: 14, roundNumber: 3, question: "What is the most popular sport?", answer: "Soccer" },
			{ id: 15, roundNumber: 3, question: "What is the Super Bowl?", answer: "NFL championship" },
			{ id: 16, roundNumber: 3, question: "What is the Olympics?", answer: "International sports competition" },
			{ id: 17, roundNumber: 3, question: "What is the Tour de France?", answer: "Cycling race" },
			{ id: 18, roundNumber: 3, question: "What is Wimbledon?", answer: "Tennis tournament" },
			{ id: 19, roundNumber: 4, question: "What is TikTok?", answer: "Social media app" },
			{ id: 20, roundNumber: 4, question: "What is the most popular streaming service?", answer: "Netflix" },
			{ id: 21, roundNumber: 4, question: "What is a meme?", answer: "Internet joke" },
			{ id: 22, roundNumber: 4, question: "What is the most popular social media?", answer: "Facebook" },
			{ id: 23, roundNumber: 4, question: "What is a viral video?", answer: "Popular online video" },
			{ id: 24, roundNumber: 4, question: "What is an influencer?", answer: "Social media personality" },
			{ id: 25, roundNumber: 5, question: "What is entertainment?", answer: "Fun activities" },
		]
	},
	"7": {
		rounds: [
			{ number: 1, title: "World Wonders", blurb: "Amazing places around the world!" },
			{ number: 2, title: "Historical Events", blurb: "Important moments in history." },
			{ number: 3, title: "Science Facts", blurb: "Fascinating scientific discoveries." },
			{ number: 4, title: "Geography", blurb: "Explore the world!" },
			{ number: 5, title: "Nature", blurb: "The natural world." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What are the Seven Wonders?", answer: "Ancient landmarks" },
			{ id: 2, roundNumber: 1, question: "What is the Great Wall of China?", answer: "Ancient fortification" },
			{ id: 3, roundNumber: 1, question: "What is Machu Picchu?", answer: "Incan citadel" },
			{ id: 4, roundNumber: 1, question: "What is the Taj Mahal?", answer: "Mausoleum in India" },
			{ id: 5, roundNumber: 1, question: "What is the Colosseum?", answer: "Ancient Roman amphitheater" },
			{ id: 6, roundNumber: 1, question: "What is Stonehenge?", answer: "Prehistoric monument" },
			{ id: 7, roundNumber: 2, question: "When did World War I start?", answer: "1914" },
			{ id: 8, roundNumber: 2, question: "When did World War II end?", answer: "1945" },
			{ id: 9, roundNumber: 2, question: "When did the Berlin Wall fall?", answer: "1989" },
			{ id: 10, roundNumber: 2, question: "When did humans land on the moon?", answer: "1969" },
			{ id: 11, roundNumber: 2, question: "When was the Declaration of Independence signed?", answer: "1776" },
			{ id: 12, roundNumber: 2, question: "When did the Renaissance begin?", answer: "14th century" },
			{ id: 13, roundNumber: 3, question: "What is the speed of light?", answer: "299,792 km/s" },
			{ id: 14, roundNumber: 3, question: "What is gravity?", answer: "Force of attraction" },
			{ id: 15, roundNumber: 3, question: "What is DNA?", answer: "Genetic material" },
			{ id: 16, roundNumber: 3, question: "What is photosynthesis?", answer: "Plant process" },
			{ id: 17, roundNumber: 3, question: "What is the periodic table?", answer: "Element chart" },
			{ id: 18, roundNumber: 3, question: "What is an atom?", answer: "Basic unit of matter" },
			{ id: 19, roundNumber: 4, question: "What is the largest ocean?", answer: "Pacific" },
			{ id: 20, roundNumber: 4, question: "What is the highest mountain?", answer: "Mount Everest" },
			{ id: 21, roundNumber: 4, question: "What is the longest river?", answer: "Nile" },
			{ id: 22, roundNumber: 4, question: "What is the largest desert?", answer: "Antarctica" },
			{ id: 23, roundNumber: 4, question: "What is the smallest country?", answer: "Vatican City" },
			{ id: 24, roundNumber: 4, question: "What is the largest country?", answer: "Russia" },
			{ id: 25, roundNumber: 5, question: "What is biodiversity?", answer: "Variety of life" },
		]
	},
	"6": {
		rounds: [
			{ number: 1, title: "Literature Classics", blurb: "Great works of literature." },
			{ number: 2, title: "Music Legends", blurb: "Iconic musicians and songs." },
			{ number: 3, title: "Art Movements", blurb: "Famous art styles and periods." },
			{ number: 4, title: "Cultural Icons", blurb: "Influential cultural figures." },
			{ number: 5, title: "Humanities", blurb: "The study of human culture." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "Who wrote Romeo and Juliet?", answer: "Shakespeare" },
			{ id: 2, roundNumber: 1, question: "Who wrote 1984?", answer: "George Orwell" },
			{ id: 3, roundNumber: 1, question: "Who wrote Pride and Prejudice?", answer: "Jane Austen" },
			{ id: 4, roundNumber: 1, question: "Who wrote Moby-Dick?", answer: "Herman Melville" },
			{ id: 5, roundNumber: 1, question: "Who wrote The Great Gatsby?", answer: "F. Scott Fitzgerald" },
			{ id: 6, roundNumber: 1, question: "Who wrote To Kill a Mockingbird?", answer: "Harper Lee" },
			{ id: 7, roundNumber: 2, question: "Who is the King of Rock?", answer: "Elvis Presley" },
			{ id: 8, roundNumber: 2, question: "Who sang Thriller?", answer: "Michael Jackson" },
			{ id: 9, roundNumber: 2, question: "What band sang Bohemian Rhapsody?", answer: "Queen" },
			{ id: 10, roundNumber: 2, question: "Who is the Beatles?", answer: "British band" },
			{ id: 11, roundNumber: 2, question: "Who sang Like a Rolling Stone?", answer: "Bob Dylan" },
			{ id: 12, roundNumber: 2, question: "Who is the Queen of Pop?", answer: "Madonna" },
			{ id: 13, roundNumber: 3, question: "What is Impressionism?", answer: "Art movement" },
			{ id: 14, roundNumber: 3, question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
			{ id: 15, roundNumber: 3, question: "What is Cubism?", answer: "Art style" },
			{ id: 16, roundNumber: 3, question: "Who painted Starry Night?", answer: "Van Gogh" },
			{ id: 17, roundNumber: 3, question: "What is Surrealism?", answer: "Art movement" },
			{ id: 18, roundNumber: 3, question: "Who painted The Scream?", answer: "Edvard Munch" },
			{ id: 19, roundNumber: 4, question: "Who is a cultural icon?", answer: "Influential person" },
			{ id: 20, roundNumber: 4, question: "What is pop culture?", answer: "Popular culture" },
			{ id: 21, roundNumber: 4, question: "What is a trendsetter?", answer: "Style leader" },
			{ id: 22, roundNumber: 4, question: "What is an influencer?", answer: "Social media personality" },
			{ id: 23, roundNumber: 4, question: "What is a celebrity?", answer: "Famous person" },
			{ id: 24, roundNumber: 4, question: "What is fame?", answer: "Widespread recognition" },
			{ id: 25, roundNumber: 5, question: "What are the humanities?", answer: "Academic disciplines" },
		]
	},
	"5": {
		rounds: [
			{ number: 1, title: "Space Exploration", blurb: "Journey to the stars!" },
			{ number: 2, title: "Ocean Depths", blurb: "Dive into the deep blue." },
			{ number: 3, title: "Animal Kingdom", blurb: "Amazing creatures." },
			{ number: 4, title: "Natural Phenomena", blurb: "Nature's wonders." },
			{ number: 5, title: "Science", blurb: "Scientific discoveries." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "Who was the first person in space?", answer: "Yuri Gagarin" },
			{ id: 2, roundNumber: 1, question: "What is the closest planet to Earth?", answer: "Venus" },
			{ id: 3, roundNumber: 1, question: "What is a black hole?", answer: "Space phenomenon" },
			{ id: 4, roundNumber: 1, question: "What is the largest planet?", answer: "Jupiter" },
			{ id: 5, roundNumber: 1, question: "What is a galaxy?", answer: "Star system" },
			{ id: 6, roundNumber: 1, question: "What is the Milky Way?", answer: "Our galaxy" },
			{ id: 7, roundNumber: 2, question: "What is the deepest ocean?", answer: "Pacific" },
			{ id: 8, roundNumber: 2, question: "What is the Mariana Trench?", answer: "Deepest point" },
			{ id: 9, roundNumber: 2, question: "What lives in the deep ocean?", answer: "Various creatures" },
			{ id: 10, roundNumber: 2, question: "What is a coral reef?", answer: "Ocean ecosystem" },
			{ id: 11, roundNumber: 2, question: "What is the largest ocean?", answer: "Pacific" },
			{ id: 12, roundNumber: 2, question: "What is an octopus?", answer: "Sea creature" },
			{ id: 13, roundNumber: 3, question: "What is the largest animal?", answer: "Blue whale" },
			{ id: 14, roundNumber: 3, question: "What is the fastest animal?", answer: "Cheetah" },
			{ id: 15, roundNumber: 3, question: "What is the smallest mammal?", answer: "Bumblebee bat" },
			{ id: 16, roundNumber: 3, question: "What is a mammal?", answer: "Warm-blooded animal" },
			{ id: 17, roundNumber: 3, question: "What is a reptile?", answer: "Cold-blooded animal" },
			{ id: 18, roundNumber: 3, question: "What is a bird?", answer: "Feathered animal" },
			{ id: 19, roundNumber: 4, question: "What is a tornado?", answer: "Weather phenomenon" },
			{ id: 20, roundNumber: 4, question: "What is an earthquake?", answer: "Ground shaking" },
			{ id: 21, roundNumber: 4, question: "What is a volcano?", answer: "Mountain that erupts" },
			{ id: 22, roundNumber: 4, question: "What is the aurora?", answer: "Northern lights" },
			{ id: 23, roundNumber: 4, question: "What is a rainbow?", answer: "Light refraction" },
			{ id: 24, roundNumber: 4, question: "What is lightning?", answer: "Electrical discharge" },
			{ id: 25, roundNumber: 5, question: "What is science?", answer: "Study of nature" },
		]
	},
	"4": {
		rounds: [
			{ number: 1, title: "Food & Drink", blurb: "Culinary delights!" },
			{ number: 2, title: "Cooking Techniques", blurb: "Kitchen skills." },
			{ number: 3, title: "World Cuisines", blurb: "Global flavors." },
			{ number: 4, title: "Culinary History", blurb: "Food through time." },
			{ number: 5, title: "Culture", blurb: "Food traditions." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What is pasta?", answer: "Italian food" },
			{ id: 2, roundNumber: 1, question: "What is sushi?", answer: "Japanese food" },
			{ id: 3, roundNumber: 1, question: "What is pizza?", answer: "Italian dish" },
			{ id: 4, roundNumber: 1, question: "What is curry?", answer: "Spiced dish" },
			{ id: 5, roundNumber: 1, question: "What is bread?", answer: "Baked food" },
			{ id: 6, roundNumber: 1, question: "What is cheese?", answer: "Dairy product" },
			{ id: 7, roundNumber: 2, question: "What is sautéing?", answer: "Cooking method" },
			{ id: 8, roundNumber: 2, question: "What is baking?", answer: "Oven cooking" },
			{ id: 9, roundNumber: 2, question: "What is grilling?", answer: "Cooking on fire" },
			{ id: 10, roundNumber: 2, question: "What is boiling?", answer: "Cooking in water" },
			{ id: 11, roundNumber: 2, question: "What is frying?", answer: "Cooking in oil" },
			{ id: 12, roundNumber: 2, question: "What is roasting?", answer: "Oven cooking" },
			{ id: 13, roundNumber: 3, question: "What is Italian cuisine?", answer: "Food from Italy" },
			{ id: 14, roundNumber: 3, question: "What is French cuisine?", answer: "Food from France" },
			{ id: 15, roundNumber: 3, question: "What is Chinese cuisine?", answer: "Food from China" },
			{ id: 16, roundNumber: 3, question: "What is Mexican cuisine?", answer: "Food from Mexico" },
			{ id: 17, roundNumber: 3, question: "What is Indian cuisine?", answer: "Food from India" },
			{ id: 18, roundNumber: 3, question: "What is Japanese cuisine?", answer: "Food from Japan" },
			{ id: 19, roundNumber: 4, question: "When was cooking invented?", answer: "Ancient times" },
			{ id: 20, roundNumber: 4, question: "What is a recipe?", answer: "Cooking instructions" },
			{ id: 21, roundNumber: 4, question: "What is a chef?", answer: "Professional cook" },
			{ id: 22, roundNumber: 4, question: "What is a restaurant?", answer: "Eating establishment" },
			{ id: 23, roundNumber: 4, question: "What is fast food?", answer: "Quick service food" },
			{ id: 24, roundNumber: 4, question: "What is fine dining?", answer: "Upscale restaurant" },
			{ id: 25, roundNumber: 5, question: "What is food culture?", answer: "Culinary traditions" },
		]
	},
	"3": {
		rounds: [
			{ number: 1, title: "Sports Legends", blurb: "Iconic athletes." },
			{ number: 2, title: "Olympic Moments", blurb: "Olympic history." },
			{ number: 3, title: "World Records", blurb: "Amazing achievements." },
			{ number: 4, title: "Athletic Achievements", blurb: "Sports accomplishments." },
			{ number: 5, title: "Achievement", blurb: "Reaching goals." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "Who is the greatest athlete?", answer: "Various" },
			{ id: 2, roundNumber: 1, question: "Who won the most medals?", answer: "Various" },
			{ id: 3, roundNumber: 1, question: "Who is the fastest runner?", answer: "Usain Bolt" },
			{ id: 4, roundNumber: 1, question: "Who is the best soccer player?", answer: "Various" },
			{ id: 5, roundNumber: 1, question: "Who is the best basketball player?", answer: "Various" },
			{ id: 6, roundNumber: 1, question: "Who is the best tennis player?", answer: "Various" },
			{ id: 7, roundNumber: 2, question: "When were the first Olympics?", answer: "776 BC" },
			{ id: 8, roundNumber: 2, question: "Where were the 2020 Olympics?", answer: "Tokyo" },
			{ id: 9, roundNumber: 2, question: "What is the Olympic motto?", answer: "Faster, Higher, Stronger" },
			{ id: 10, roundNumber: 2, question: "What are the Olympic rings?", answer: "Symbol" },
			{ id: 11, roundNumber: 2, question: "What is the Olympic flame?", answer: "Torch" },
			{ id: 12, roundNumber: 2, question: "What is a gold medal?", answer: "First place" },
			{ id: 13, roundNumber: 3, question: "What is the world record?", answer: "Best achievement" },
			{ id: 14, roundNumber: 3, question: "Who holds the most records?", answer: "Various" },
			{ id: 15, roundNumber: 3, question: "What is the fastest speed?", answer: "Various" },
			{ id: 16, roundNumber: 3, question: "What is the longest distance?", answer: "Various" },
			{ id: 17, roundNumber: 3, question: "What is the highest jump?", answer: "Various" },
			{ id: 18, roundNumber: 3, question: "What is the longest time?", answer: "Various" },
			{ id: 19, roundNumber: 4, question: "What is an achievement?", answer: "Accomplishment" },
			{ id: 20, roundNumber: 4, question: "What is a championship?", answer: "Tournament" },
			{ id: 21, roundNumber: 4, question: "What is a trophy?", answer: "Award" },
			{ id: 22, roundNumber: 4, question: "What is a medal?", answer: "Award" },
			{ id: 23, roundNumber: 4, question: "What is a record?", answer: "Best performance" },
			{ id: 24, roundNumber: 4, question: "What is a victory?", answer: "Win" },
			{ id: 25, roundNumber: 5, question: "What is achievement?", answer: "Success" },
		]
	},
	"2": {
		rounds: [
			{ number: 1, title: "Mathematics Puzzles", blurb: "Brain teasers!" },
			{ number: 2, title: "Logic Problems", blurb: "Think logically." },
			{ number: 3, title: "Number Patterns", blurb: "Find the pattern." },
			{ number: 4, title: "Brain Teasers", blurb: "Challenge your mind." },
			{ number: 5, title: "Patterns", blurb: "Recognize sequences." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "What is 2 + 2?", answer: "4" },
			{ id: 2, roundNumber: 1, question: "What is 10 × 10?", answer: "100" },
			{ id: 3, roundNumber: 1, question: "What is the square root of 16?", answer: "4" },
			{ id: 4, roundNumber: 1, question: "What is π?", answer: "3.14159..." },
			{ id: 5, roundNumber: 1, question: "What is 100 ÷ 4?", answer: "25" },
			{ id: 6, roundNumber: 1, question: "What is 5²?", answer: "25" },
			{ id: 7, roundNumber: 2, question: "If all A are B, and all B are C, then?", answer: "All A are C" },
			{ id: 8, roundNumber: 2, question: "What is logic?", answer: "Reasoning" },
			{ id: 9, roundNumber: 2, question: "What is a syllogism?", answer: "Logical argument" },
			{ id: 10, roundNumber: 2, question: "What is deduction?", answer: "Logical reasoning" },
			{ id: 11, roundNumber: 2, question: "What is induction?", answer: "Reasoning method" },
			{ id: 12, roundNumber: 2, question: "What is a paradox?", answer: "Contradiction" },
			{ id: 13, roundNumber: 3, question: "What comes next: 2, 4, 6, 8?", answer: "10" },
			{ id: 14, roundNumber: 3, question: "What comes next: 1, 4, 9, 16?", answer: "25" },
			{ id: 15, roundNumber: 3, question: "What comes next: 1, 1, 2, 3, 5?", answer: "8" },
			{ id: 16, roundNumber: 3, question: "What comes next: 2, 4, 8, 16?", answer: "32" },
			{ id: 17, roundNumber: 3, question: "What comes next: 1, 3, 5, 7?", answer: "9" },
			{ id: 18, roundNumber: 3, question: "What comes next: 10, 20, 30, 40?", answer: "50" },
			{ id: 19, roundNumber: 4, question: "What is a puzzle?", answer: "Brain challenge" },
			{ id: 20, roundNumber: 4, question: "What is a riddle?", answer: "Puzzle question" },
			{ id: 21, roundNumber: 4, question: "What is a conundrum?", answer: "Difficult problem" },
			{ id: 22, roundNumber: 4, question: "What is an enigma?", answer: "Mystery" },
			{ id: 23, roundNumber: 4, question: "What is a brain teaser?", answer: "Mental challenge" },
			{ id: 24, roundNumber: 4, question: "What is a challenge?", answer: "Difficult task" },
			{ id: 25, roundNumber: 5, question: "What is a pattern?", answer: "Repeating sequence" },
		]
	},
	"1": {
		rounds: [
			{ number: 1, title: "Famous Inventions", blurb: "Revolutionary creations!" },
			{ number: 2, title: "Scientific Discoveries", blurb: "Groundbreaking findings." },
			{ number: 3, title: "Medical Breakthroughs", blurb: "Life-saving advances." },
			{ number: 4, title: "Innovation", blurb: "New ideas and technologies." },
			{ number: 5, title: "Discovery", blurb: "Finding something new." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
			{ id: 2, roundNumber: 1, question: "Who invented the light bulb?", answer: "Thomas Edison" },
			{ id: 3, roundNumber: 1, question: "Who invented the internet?", answer: "Various" },
			{ id: 4, roundNumber: 1, question: "Who invented the computer?", answer: "Various" },
			{ id: 5, roundNumber: 1, question: "Who invented the airplane?", answer: "Wright Brothers" },
			{ id: 6, roundNumber: 1, question: "Who invented the printing press?", answer: "Gutenberg" },
			{ id: 7, roundNumber: 2, question: "What is gravity?", answer: "Force of attraction" },
			{ id: 8, roundNumber: 2, question: "What is DNA?", answer: "Genetic material" },
			{ id: 9, roundNumber: 2, question: "What is evolution?", answer: "Species change" },
			{ id: 10, roundNumber: 2, question: "What is relativity?", answer: "Einstein's theory" },
			{ id: 11, roundNumber: 2, question: "What is quantum mechanics?", answer: "Physics theory" },
			{ id: 12, roundNumber: 2, question: "What is the periodic table?", answer: "Element chart" },
			{ id: 13, roundNumber: 3, question: "What is penicillin?", answer: "Antibiotic" },
			{ id: 14, roundNumber: 3, question: "What is vaccination?", answer: "Disease prevention" },
			{ id: 15, roundNumber: 3, question: "What is anesthesia?", answer: "Pain relief" },
			{ id: 16, roundNumber: 3, question: "What is surgery?", answer: "Medical procedure" },
			{ id: 17, roundNumber: 3, question: "What is a vaccine?", answer: "Disease prevention" },
			{ id: 18, roundNumber: 3, question: "What is medicine?", answer: "Treatment" },
			{ id: 19, roundNumber: 4, question: "What is innovation?", answer: "New idea" },
			{ id: 20, roundNumber: 4, question: "What is technology?", answer: "Applied science" },
			{ id: 21, roundNumber: 4, question: "What is a startup?", answer: "New company" },
			{ id: 22, roundNumber: 4, question: "What is an invention?", answer: "New creation" },
			{ id: 23, roundNumber: 4, question: "What is a patent?", answer: "Invention protection" },
			{ id: 24, roundNumber: 4, question: "What is research?", answer: "Scientific study" },
			{ id: 25, roundNumber: 5, question: "What is discovery?", answer: "Finding something new" },
		]
	},
	"277": {
		rounds: [
			{ number: 1, title: "Back to the Past", blurb: "Journey through history's most memorable moments!" },
			{ number: 2, title: "Name That Nation", blurb: "Test your geography and world knowledge." },
			{ number: 3, title: "Name the Other", blurb: "Can you identify the missing piece of these famous pairs?" },
			{ number: 4, title: "Analog Games", blurb: "Before screens took over, these games ruled!" },
			{ number: 5, title: "What Does It Stand For?", blurb: "Decode these acronyms and abbreviations." },
		],
		questions: [
			{ id: 1, roundNumber: 1, question: "In what year did World War II end?", answer: "1945" },
			{ id: 2, roundNumber: 1, question: "When did the Berlin Wall fall?", answer: "1989" },
			{ id: 3, roundNumber: 1, question: "What year did humans first land on the moon?", answer: "1969" },
			{ id: 4, roundNumber: 1, question: "When was the Declaration of Independence signed?", answer: "1776" },
			{ id: 5, roundNumber: 1, question: "In what year did the Titanic sink?", answer: "1912" },
			{ id: 6, roundNumber: 1, question: "What year did the internet become publicly available?", answer: "1991" },
			{ id: 7, roundNumber: 2, question: "What is the capital of Japan?", answer: "Tokyo" },
			{ id: 8, roundNumber: 2, question: "Which country has the most pyramids?", answer: "Sudan" },
			{ id: 9, roundNumber: 2, question: "What is the smallest country in the world?", answer: "Vatican City" },
			{ id: 10, roundNumber: 2, question: "Which nation has the longest coastline?", answer: "Canada" },
			{ id: 11, roundNumber: 2, question: "In which country is the ancient city of Petra?", answer: "Jordan" },
			{ id: 12, roundNumber: 2, question: "What is the largest country by land area?", answer: "Russia" },
			{ id: 13, roundNumber: 3, question: "Simon & __?", answer: "Garfunkel" },
			{ id: 14, roundNumber: 3, question: "Romeo & __?", answer: "Juliet" },
			{ id: 15, roundNumber: 3, question: "Batman & __?", answer: "Robin" },
			{ id: 16, roundNumber: 3, question: "Bonnie & __?", answer: "Clyde" },
			{ id: 17, roundNumber: 3, question: "Salt & __?", answer: "Pepper" },
			{ id: 18, roundNumber: 3, question: "Tom & __?", answer: "Jerry" },
			{ id: 19, roundNumber: 4, question: "What board game involves buying property?", answer: "Monopoly" },
			{ id: 20, roundNumber: 4, question: "In which game do you sink your opponent's fleet?", answer: "Battleship" },
			{ id: 21, roundNumber: 4, question: "What game uses colored cards with numbers?", answer: "UNO" },
			{ id: 22, roundNumber: 4, question: "Which game involves removing wooden blocks?", answer: "Jenga" },
			{ id: 23, roundNumber: 4, question: "What strategy game uses black and white stones?", answer: "Go" },
			{ id: 24, roundNumber: 4, question: "What card game involves matching sets?", answer: "Rummy" },
			{ id: 25, roundNumber: 5, question: "What does NASA stand for?", answer: "National Aeronautics and Space Administration" },
		]
	}
};

export default function QuizPlayPage() {
	const params = useParams();
	const router = useRouter();
	const slug = String(params?.slug ?? "");
	const quiz = DATA.find((q) => q.slug === slug);
	const quizData = QUIZ_DATA[slug];
	
	useEffect(() => {
		if (!quiz || !quizData) {
			router.replace("/quizzes");
		}
	}, [quiz, quizData, router]);

	if (!quiz || !quizData) return null;

	const isNewest = DATA[0].slug === quiz.slug;

	return (
		<QuizPlayer
			quizTitle={quiz.title}
			quizColor={quiz.colorHex}
			quizSlug={quiz.slug}
			questions={quizData.questions}
			rounds={quizData.rounds}
			weekISO={quiz.weekISO}
			isNewest={isNewest}
		/>
	);
}
