// Dummy data for billing pages

export const dummyBillingData = {
  subscriptions: [
    {
      id: 'sub-1',
      organisationId: 'org-1',
      organisationName: 'Melbourne High School',
      plan: 'ORG_ANNUAL',
      status: 'ACTIVE',
      amount: 12000, // $120.00 in cents
      currency: 'AUD',
      currentPeriodStart: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 350 * 24 * 60 * 60 * 1000).toISOString(),
      cancelAtPeriodEnd: false,
      seats: 150,
      maxSeats: 200,
      stripeCustomerId: 'cus_melbournehigh',
      stripeSubscriptionId: 'sub_melbournehigh',
    },
    {
      id: 'sub-2',
      organisationId: 'org-2',
      organisationName: 'Sydney Grammar School',
      plan: 'ORG_MONTHLY',
      status: 'ACTIVE',
      amount: 1200, // $12.00 in cents
      currency: 'AUD',
      currentPeriodStart: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      cancelAtPeriodEnd: false,
      seats: 134,
      maxSeats: 150,
      stripeCustomerId: 'cus_sydneygrammar',
      stripeSubscriptionId: 'sub_sydneygrammar',
    },
    {
      id: 'sub-3',
      organisationId: 'org-3',
      organisationName: 'Brisbane Grammar',
      plan: 'ORG_ANNUAL',
      status: 'PAST_DUE',
      amount: 12000,
      currency: 'AUD',
      currentPeriodStart: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 335 * 24 * 60 * 60 * 1000).toISOString(),
      cancelAtPeriodEnd: false,
      seats: 98,
      maxSeats: 100,
      stripeCustomerId: 'cus_brisbanegrammar',
      stripeSubscriptionId: 'sub_brisbanegrammar',
    },
    {
      id: 'sub-4',
      organisationId: 'org-4',
      organisationName: 'Trial School',
      plan: 'INDIVIDUAL',
      status: 'TRIALING',
      amount: 0,
      currency: 'AUD',
      currentPeriodStart: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      cancelAtPeriodEnd: false,
      seats: 67,
      maxSeats: 0,
      stripeCustomerId: null,
      stripeSubscriptionId: null,
    },
  ],
  invoices: [
    {
      id: 'inv-1',
      organisationId: 'org-1',
      organisationName: 'Melbourne High School',
      amount: 12000,
      currency: 'AUD',
      status: 'PAID',
      invoiceDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      paidDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      stripeInvoiceId: 'in_melbournehigh_001',
      pdfUrl: '#',
    },
    {
      id: 'inv-2',
      organisationId: 'org-2',
      organisationName: 'Sydney Grammar School',
      amount: 1200,
      currency: 'AUD',
      status: 'PAID',
      invoiceDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      paidDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      stripeInvoiceId: 'in_sydneygrammar_001',
      pdfUrl: '#',
    },
    {
      id: 'inv-3',
      organisationId: 'org-3',
      organisationName: 'Brisbane Grammar',
      amount: 12000,
      currency: 'AUD',
      status: 'OVERDUE',
      invoiceDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      paidDate: null,
      stripeInvoiceId: 'in_brisbanegrammar_001',
      pdfUrl: '#',
    },
  ],
  revenue: {
    thisMonth: 13200, // $132.00
    lastMonth: 12000, // $120.00
    thisYear: 144000, // $1,440.00
    change: 10.0,
  },
}

export const dummyWebhookEvents = [
  {
    id: 'evt-1',
    type: 'customer.subscription.created',
    status: 'SUCCEEDED',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    organisationId: 'org-1',
    organisationName: 'Melbourne High School',
    payload: { subscription_id: 'sub_melbournehigh', plan: 'ORG_ANNUAL' },
  },
  {
    id: 'evt-2',
    type: 'invoice.payment_succeeded',
    status: 'SUCCEEDED',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    organisationId: 'org-1',
    organisationName: 'Melbourne High School',
    payload: { invoice_id: 'in_melbournehigh_001', amount: 12000 },
  },
  {
    id: 'evt-3',
    type: 'invoice.payment_failed',
    status: 'SUCCEEDED',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    organisationId: 'org-3',
    organisationName: 'Brisbane Grammar',
    payload: { invoice_id: 'in_brisbanegrammar_001', amount: 12000 },
  },
  {
    id: 'evt-4',
    type: 'customer.subscription.updated',
    status: 'SUCCEEDED',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    organisationId: 'org-2',
    organisationName: 'Sydney Grammar School',
    payload: { subscription_id: 'sub_sydneygrammar', plan: 'ORG_MONTHLY' },
  },
]

export const dummySupportTickets = [
  {
    id: 'ticket-1',
    subject: 'Unable to create organisation',
    status: 'OPEN',
    priority: 'HIGH',
    category: 'TECHNICAL',
    organisationId: 'org-1',
    organisationName: 'Melbourne High School',
    userId: 'user-1',
    userName: 'Sarah Johnson',
    userEmail: 'sarah@melbournehigh.edu.au',
    message: 'I am unable to create a new organisation. The form keeps showing an error.',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: null,
    replies: [],
  },
  {
    id: 'ticket-2',
    subject: 'Billing question about annual plan',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    category: 'BILLING',
    organisationId: 'org-2',
    organisationName: 'Sydney Grammar School',
    userId: 'user-3',
    userName: 'Emma Wilson',
    userEmail: 'emma@sydneygrammar.edu.au',
    message: 'I have a question about the annual billing plan. Can we get a discount for multiple seats?',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: 'admin-1',
    replies: [
      {
        id: 'reply-1',
        message: 'Thank you for your inquiry. We do offer volume discounts for organisations with 100+ seats.',
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'admin-1',
        userName: 'Admin User',
      },
    ],
  },
  {
    id: 'ticket-3',
    subject: 'Feature request: Export quiz results',
    status: 'CLOSED',
    priority: 'LOW',
    category: 'FEATURE_REQUEST',
    organisationId: null,
    organisationName: null,
    userId: 'user-5',
    userName: 'Alex Smith',
    userEmail: 'alex@example.com',
    message: 'It would be great if we could export quiz results to CSV or Excel format.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: 'admin-1',
    replies: [
      {
        id: 'reply-2',
        message: 'Thank you for the suggestion! This feature is now available in the latest update.',
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'admin-1',
        userName: 'Admin User',
      },
    ],
  },
]

export const dummyFeatureFlags = [
  {
    id: 'flag-1',
    key: 'ENABLE_NEW_QUIZ_EDITOR',
    name: 'New Quiz Editor',
    description: 'Enable the new drag-and-drop quiz editor interface',
    enabled: true,
    enabledForOrgs: ['org-1', 'org-2'],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'flag-2',
    key: 'ENABLE_ACHIEVEMENTS',
    name: 'Achievements System',
    description: 'Enable the achievements and badges system',
    enabled: true,
    enabledForOrgs: [],
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'flag-3',
    key: 'ENABLE_ANALYTICS_DASHBOARD',
    name: 'Analytics Dashboard',
    description: 'Enable the new analytics dashboard for organisations',
    enabled: false,
    enabledForOrgs: ['org-1'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'flag-4',
    key: 'ENABLE_BULK_USER_IMPORT',
    name: 'Bulk User Import',
    description: 'Allow organisations to import users via CSV',
    enabled: true,
    enabledForOrgs: [],
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const dummyAuditLogs = [
  {
    id: 'log-1',
    action: 'USER_ROLE_UPDATED',
    userId: 'user-1',
    userName: 'Sarah Johnson',
    targetType: 'USER',
    targetId: 'user-2',
    targetName: 'John Doe',
    details: { oldRole: 'TEACHER', newRole: 'ORG_ADMIN' },
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0...',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-2',
    action: 'ORGANISATION_CREATED',
    userId: 'user-3',
    userName: 'Emma Wilson',
    targetType: 'ORGANISATION',
    targetId: 'org-5',
    targetName: 'New School',
    details: { plan: 'ORG_MONTHLY', seats: 50 },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0...',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-3',
    action: 'QUIZ_PUBLISHED',
    userId: 'user-1',
    userName: 'Sarah Johnson',
    targetType: 'QUIZ',
    targetId: 'quiz-3',
    targetName: 'Week 3 - Pop Culture & Entertainment',
    details: { scheduledFor: new Date().toISOString() },
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0...',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-4',
    action: 'SUBSCRIPTION_CANCELLED',
    userId: 'user-4',
    userName: 'Michael Brown',
    targetType: 'ORGANISATION',
    targetId: 'org-6',
    targetName: 'Cancelled School',
    details: { reason: 'User requested', effectiveDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString() },
    ipAddress: '192.168.1.102',
    userAgent: 'Mozilla/5.0...',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-5',
    action: 'FEATURE_FLAG_UPDATED',
    userId: 'admin-1',
    userName: 'Admin User',
    targetType: 'FEATURE_FLAG',
    targetId: 'flag-3',
    targetName: 'ENABLE_ANALYTICS_DASHBOARD',
    details: { oldValue: true, newValue: false },
    ipAddress: '192.168.1.1',
    userAgent: 'Mozilla/5.0...',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

